image: opensuse:latest

before_script:
- zypper ar -f -g https://download.opensuse.org/repositories/home:/HessiJames/openSUSE_Leap_42.2/home:HessiJames.repo
- zypper --gpg-auto-import-keys ref
- zypper in -y kcov curl
- zypper in -y -t pattern devel_C_C++
- curl https://sh.rustup.rs > rustup
- chmod +x rustup
- ./rustup -y

build:
  stage: build
  script:
  - ~/.cargo/bin/cargo build

doc:
  stage: build
  script:
  - ~/.cargo/bin/cargo doc
  - mv target/doc public
  artifacts:
    paths:
    - public

test:
  stage: test
  script:
  - ~/.cargo/bin/cargo test

cov:
  stage: test
  coverage: '/^Coverage+:\s(\d+(?:\.\d+)?)/'
  script:
  - ~/.cargo/bin/cargo install cargo-kcov
  - ~/.cargo/bin/cargo build
  - ~/.cargo/bin/cargo kcov
  - COVERAGE=$(grep -Po 'covered":.*?[^\\]"' target/cov/index.json | grep "[0-9]*\.[0-9]" -o)
  - echo "Coverage:" $COVERAGE
  - mv target/cov public/
  artifacts:
    paths:
    - public

pages:
  stage: deploy
  script:
  - mv index.html public/
  artifacts:
    paths:
    - public
  only:
  - master
