image: alpine:latest

pages:
  stage: deploy
  script:
  - mv docs public
  artifacts:
    paths:
    - public
  only:
  - master

test:cargo:
  image: "rust:latest"
  script:
  - rustc --version && cargo --version
  - cargo test --all --verbose
